#!/bin/bash
################################################################
#
# GUI wrapper for lglaf by
# steadfasterX <steadfastX|boun.cr>
#
################################################################

YAD=/usr/bin/yad

# the vars for the lglaf GUI
VARS=lglafgui.vars
source $VARS
[ $? -ne 0 ] && "ERROR: Missing requirement <$VARS>." && exit 3

# the functions for the lglaf GUI
FUNCS=lglafgui.func
source $FUNCS 
[ $? -ne 0 ] && "ERROR: Missing requirement <$FUNCS>." && exit 3

# check requirements:
[ ! -x $YAD ]&& F_ECHOLOG "ERROR: Missing requirement <yad>." && F_EXIT yad-missing 3


F_YAD 400 --text "test yes"


